package com.example.cuidalink.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta CuidaLink (diseño "CuidaLink App")
val CuidaGreen = Color(0xFF119B68)
val CuidaGreenDark = Color(0xFF0C7A52)
val CuidaGreenSurface = Color(0xFFE7F5EF)
val CuidaGreenSurfaceHover = Color(0xFFD2EDE1)
val CuidaTextPrimary = Color(0xFF17211C)
val CuidaTextSecondary = Color(0xFF5E6B65)
val CuidaTextDisabled = Color(0xFF9AA6A0)
val CuidaBorder = Color(0xFFE3E8E5)
val CuidaBorderLight = Color(0xFFE8ECEA)
val CuidaDivider = Color(0xFFEDF1EF)
val CuidaSurfaceMuted = Color(0xFFF4F6F5)
val CuidaSurfaceFaint = Color(0xFFFAFBFA)
val CuidaGameBackground = Color(0xFFF9FAFB)
val CuidaRed = Color(0xFFD7382F)
val CuidaRedDark = Color(0xFFB0362E)
val CuidaRedSurface = Color(0xFFFCEAE8)
val CuidaRedDeep = Color(0xFF8E2B25)
val CuidaAmberLabel = Color(0xFF94762F)
val CuidaAmberDeep = Color(0xFF755D24)
val CuidaAmber = Color(0xFFA87B2E)
val CuidaAmberSurface = Color(0xFFF7EFDF)
val CuidaBlue = Color(0xFF3E7BBF)
val CuidaBlueSurface = Color(0xFFE8F0F8)
